name: fluttermoji
description: A light-weight and highly customizable SVG graphic set for Flutter
  which generates avatars and provides a Customizer Widget, personalized
  CircleAvatar and other utility functions.
version: 0.2.2
# author: Suraj Kumar
homepage: https://github.com/psk907/fluttermoji

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  flutter_svg: ^0.23.0+1
  get: ^4.3.8
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - attributeicons/
